### PR TITLE
feat(use-find-first): add a rule to check for `findUnique` usage

### PR DESCRIPTION
**Pull request by Fluf22**
Hey,

I cleaned the yarn.lock that seemed to be crafted behind a custom registry, added the ability to use `deletedAt` key for soft-delete, and also added a new rule check to verify that `findFirst` is used instead of `findUnique`.

Tell me what you think!

Thanks,
Thomas

### CODE REVIEW

**Comment by 770shl** [comment]
About findUnique see the last release (4.5.0), there is a preview feature that allows non-unique properties in unique where queries.
https://github.com/prisma/prisma/releases/tag/4.5.0

**Comment by Fluf22** [comment]
Ah, good catch!
Here is an idea: what about releasing this as a version for people using Prisma < 4.5.0, and then I'll make another PR handling `where` in `findUnique`, so people can use the latest version of your rule with the latest version of Prisma, or select this version if they are running an older version of Prisma?
What do you think? ☺️

**Comment by sumancbd** [comment]
Hi @Fluf22, thank you for the PR. I was thinking of doing the same

**Comment by sumancbd** [comment]
Also the eslint server crashes if findMany is used with a variable that has the finaMany arguments instead of directly writing it. I will try to provide a fix this weekend

```
this.prismaService.product.findMany({
        ...query,
        ...this.utilService.dbQueryToPaginate(page, limit),
        orderBy: {
          [orderByKey]: orderByDirection,
        },
      }),
```

**Pull request merged**
